---
- hosts: localhost
  connection: local
  vars_files:
    - creds.yml
  tasks:
    - name: Get Auth Token
      uri:
        url: "https://{{ provider.server }}{{ authUrl }}"
        method: POST
        body_format: json
        return_content: true
        validate_certs: false
        body: {"username":"{{ provider.user }}","password":"{{ provider.password }}","loginProviderName":"tmos"}
        status_code: 200
      register: token
      retries: 3
      delay: 30
      delegate_to: localhost
      tags:
        - uploads
        - status
        - as3install
        - doinstall
        - tsinstall
        - fastinstall

    - name: Check AS3 status
      uri:
        url: "https://{{ provider.server }}{{ as3CheckUrl }}"
        method: GET
        headers:
          X-F5-Auth-Token: "{{ token.json.token.token }}"
        return_content: true
        validate_certs: false
        status_code: 200
      register: as3_check
      delegate_to: localhost
      when: token.json.token.token == ""
      tags:
        - uploads
        - status

    - name: Check DO status
      uri:
        url: "https://{{ provider.server }}{{ doCheckUrl }}"
        method: GET
        headers:
          X-F5-Auth-Token: "{{ token.json.token.token }}"
        return_content: true
        validate_certs: false
        status_code: 200
      register: do_check
      delegate_to: localhost
      when: token.json.token.token == ""
      tags:
        - uploads
        - status

    - name: Check TS status
      uri:
        url: "https://{{ provider.server }}{{ tsCheckUrl }}"
        method: GET
        headers:
          X-F5-Auth-Token: "{{ token.json.token.token }}"
        return_content: true
        validate_certs: false
        status_code: 200
      register: ts_check
      delegate_to: localhost
      when: token.json.token.token == ""
      tags:
        - uploads
        - status

    - name: Check FAST status
      uri:
        url: "https://{{ provider.server }}{{ fastCheckUrl }}"
        method: GET
        headers:
          X-F5-Auth-Token: "{{ token.json.token.token }}"
        return_content: true
        validate_certs: false
        status_code: 200
      register: fast_check
      delegate_to: localhost
      when: token.json.token.token == ""
      tags:
        - uploads
        - status

    - name: Retrieve AS3 Install Version
      find:
        paths: "{{ filePath }}"
        patterns: "f5-appsvcs*.rpm"
      register: as3rpm
      delegate_to: localhost
      tags:
        - as3install

    - name: Retrieve DO Install Version
      find:
        paths: "{{ filePath }}"
        patterns: "f5-dec*.rpm"
      register: dorpm
      delegate_to: localhost
      tags:
        - doinstall

    - name: Retrieve TS Install Version
      find:
        paths: "{{ filePath }}"
        patterns: "f5-tele*.rpm"
      register: tsrpm
      delegate_to: localhost
      tags:
        - tsinstall

    - name: Retrieve FAST Install Version
      find:
        paths: "{{ filePath }}"
        patterns: "f5-appsvcs-temp*.rpm"
      register: fastrpm
      delegate_to: localhost
      tags:
        - fastinstall

    - name: pause 5 sec
      pause:
        seconds: 5

    - name: Install DO RPM
      bigip_lx_package:
         provider: "{{ provider  }}"
         package: "{{ dorpm.files[0].path }}"
      delegate_to: localhost

    - name: Install AS3 RPM
      bigip_lx_package:
        provider: "{{ provider }}"
        package: "{{ as3rpm.files[0].path }}"
      delegate_to: localhost
      tags:
        - as3install

    - name: Install TS RPM
      bigip_lx_package:
        provider: "{{ provider }}"
        package: "{{ tsrpm.files[0].path }}"
      delegate_to: localhost
      tags:
        - tsinstall

    - name: Install FAST RPM
      bigip_lx_package:
        provider: "{{ provider }}"
        package: "{{ fastrpm.files[0].path }}"
      delegate_to: localhost
      tags:
        - fastinstall